### ISSUE TITLE
out of range during rendering

### ISSUE THREAD

**Issue by zhihaozheng** [YuelongWu/feabas#3]
Not sure if it's a bug but I get this out of range error with scale=0.5 or resolution=8 while attempting to render at mip 1.

`OUT_OF_RANGE: Computing interval slice for dimension 1: Slice interval [155648, 163840) is not contained within domain [0, 162292) [source locations='tensorstore/index_interval.cc:401\ntensorstore/index_space/internal/numpy_indexing_spec.cc:501\ntensorstore/index_space/internal/numpy_indexing_spec.cc:501\ntensorstore/index_space.h:429']`

**Comment by YuelongWu** [comment]
Yep, a bug. I've made a quick fix for rendering step of the stitching. Will follow up later to fix further inconsistencies in the

**Comment by zhihaozheng** [comment]
It didn't report an error any more but there some chunks that are still not written out (black chunk) when resolution set to 8.

**Comment by zhihaozheng** [comment]
Also it seems writing out to mip1 didn't save any time in the rendering step, compared to mip0

**Comment by YuelongWu** [comment]
I tested on our machine, mip1 renders ~3 times faster than mip0, and no missing chunks.. Could you share your config file and neuroglancer info file? Is there a pattern in the missing chunk locations?
