### ISSUE TITLE
spacing(s)

### ISSUE THREAD

**Issue by zhihaozheng** [YuelongWu/feabas#4]
I suppose spacing in the stitching config file should has "s" https://github.com/YuelongWu/feabas/blob/62b8493a1ec866b7adb0c772d21027865553b49e/configs/default_stitching_configs.yaml#L10, because [stitching_matcher](https://github.com/YuelongWu/feabas/blob/62b8493a1ec866b7adb0c772d21027865553b49e/feabas/matcher.py#L176) is getting `spacings`

**Comment by YuelongWu** [comment]
you're right, thanks!
